[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "permit2/=lib/permit2/",
    "@openzeppelin/contracts-upgradeable/=lib/protocol-contracts/node_modules/@openzeppelin/contracts-upgradeable/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"